<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-U9BEVS1" ignored="3" name="Test" tests="1" failures="1" timestamp="2021-09-02T21:01:37 IST" time="34.511" errors="0">
  <testcase name="VerifyRatingSucessMessage" time="19.749" classname="com.openkart.Testclass.TC_ProductDisplay">
    <failure type="java.lang.AssertionError" message="expected [ Thank you for your review. It has been submitted to the webmaster for approval.] but found [Your Name]">
      <![CDATA[java.lang.AssertionError: expected [ Thank you for your review. It has been submitted to the webmaster for approval.] but found [Your Name]
at com.openkart.Testclass.TC_ProductDisplay.VerifyRatingSucessMessage(TC_ProductDisplay.java:63)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- VerifyRatingSucessMessage -->
  <testcase name="VerifyAvailabilityStatus" time="0.0" classname="com.openkart.Testclass.TC_ProductDisplay">
    <ignored/>
  </testcase> <!-- VerifyAvailabilityStatus -->
  <testcase name="VerifyTheBrandNameCodeProductName_001" time="0.0" classname="com.openkart.Testclass.TC_ProductDisplay">
    <ignored/>
  </testcase> <!-- VerifyTheBrandNameCodeProductName_001 -->
  <testcase name="VerifyTheDefaultQuantiyOne" time="0.0" classname="com.openkart.Testclass.TC_ProductDisplay">
    <ignored/>
  </testcase> <!-- VerifyTheDefaultQuantiyOne -->
</testsuite> <!-- Test -->
